// Copyright 2026 A. Shannon
// SPDX-License-Identifier: Apache-2.0

//! Closed structural catalogue for eleven recursive-ancestry row bindings.
//!
//! The bindings select seven cryptographically distinct receipts: two copied
//! from authenticated positive ancestry and five generated by the closed
//! negative producer phase.
//!
//! Parsing and validating this post-generation document does not authenticate
//! any receipt. A later derive-first replay must compare the measured bytes and
//! cryptographic result before it can construct any non-serializable authority.

use std::collections::BTreeSet;

use anyhow::{Context as _, Result, bail, ensure};
use serde::{Deserialize, Serialize};

use crate::{
    b4::{B4NegativeAncestryWitnessRecipeV1, negative_ancestry_witness_recipe},
    b4_campaign_contract::{
        B4ContractArtifactEncodingV1, B4ContractArtifactIdentityV1, validate_safe_relative_path,
    },
    b4_plan::{B4NegativeExecutionSurface, B4NegativeQaResultCode, Eip0045B4NegativePlanV1},
    canonical::{canonical_json_bytes, validate_canonical_json_source, validate_lower_hex_exact},
    constants::{
        DIGEST_BYTES, MANIFEST_BYTES, PROOF_BYTES, RISC0_INNER_CONTROL_ROOT_HEX,
        RISC0_JOIN_CONTROL_ID_HEX, RISC0_NORMAL_LIFT_CONTROL_IDS_HEX, RISC0_RESOLVE_CONTROL_ID_HEX,
    },
    receipt_oracle_codec::{RECEIPT_ORACLE_CODEC_V1, RECEIPT_ORACLE_MAX_BYTES_U64},
    recursive_ancestry::{
        RECURSIVE_ANCESTRY_FINAL_SEAL_FILE, RecursiveAncestryClaim, RecursiveAncestryFamily,
        RecursiveAncestryTerminal, recursive_ancestry_case_path, recursive_ancestry_claim_digest,
        recursive_ancestry_expected_auxiliary_paths,
    },
};

/// Exact post-generation catalogue discriminator.
pub const B4_NEGATIVE_ANCESTRY_WITNESS_CATALOG_FORMAT: &str =
    "Eip0045B4NegativeAncestryWitnessCatalogV1";
/// Exact catalogue schema version.
pub const B4_NEGATIVE_ANCESTRY_WITNESS_CATALOG_VERSION: u8 = 1;
/// Exact number of row bindings published by the catalogue.
pub const B4_NEGATIVE_ANCESTRY_BINDING_COUNT: usize = 11;
/// Exact number of files in one published negative-ancestry catalogue root.
pub const B4_NEGATIVE_ANCESTRY_PUBLICATION_FILE_COUNT: usize =
    2 + 2 * B4_NEGATIVE_ANCESTRY_BINDING_COUNT;
/// Exact number of cryptographically distinct receipts selected by those rows.
pub const B4_NEGATIVE_ANCESTRY_DISTINCT_WITNESS_COUNT: usize = 7;
/// Fixed archive-relative path of the authenticated derived catalogue.
pub use crate::b4_negative_ancestry_layout::B4_NEGATIVE_ANCESTRY_WITNESS_CATALOG_PATH;
/// Fixed negative-plan path inherited from the campaign contract.
pub const B4_NEGATIVE_ANCESTRY_PLAN_PATH: &str = "reproduction/negative-plan.json";
/// Fixed binary profile-manifest path.
pub const B4_NEGATIVE_ANCESTRY_PROFILE_MANIFEST_PATH: &str =
    "profiles/risc0-v3-succinct/manifest.bin";
/// Fixed ELF whose independently recomputed image ID produces rows 147/151.
pub const B4_NEGATIVE_ANCESTRY_ALTERNATE_GUEST_ELF_PATH: &str =
    "reproduction/negative-ancestry-witnesses/alternate-program-guest.elf";

const B4_NEGATIVE_ANCESTRY_WITNESS_ROOT: &str = "reproduction/negative-ancestry-witnesses";
const MAX_CATALOG_JCS_BYTES: usize = 128 * 1024;
const MAX_NEGATIVE_PLAN_BYTES: u64 = 128 * 1024;
const MAX_ALTERNATE_GUEST_ELF_BYTES: u64 = 4 * 1024 * 1024;

/// Closed lifecycle stage. This V1 document can exist only after generation.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum B4NegativeAncestryWitnessCatalogStageV1 {
    /// Candidate identities measured after seven recipes and eleven bindings.
    PostGenerationDerived,
}

/// Closed producer role of one witness.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum B4NegativeAncestryProducerRoleV1 {
    /// Ordinary source-segment lift.
    Lift,
    /// Lift which proves the assumption receipt selected by resolve.
    AssumptionLift,
    /// Stock join.
    Join,
    /// Stock resolve.
    Resolve,
}

/// Closed logical placement consumed by recursive ancestry replay.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum B4NegativeAncestryLogicalPlacementV1 {
    /// The family assumption receipt.
    AssumptionReceipt,
    /// Non-final ancestry step zero.
    Step0,
    /// Non-final ancestry step two.
    Step2,
    /// Final family receipt.
    FinalReceipt,
}

/// Closed identity of one cryptographically distinct receipt witness.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum B4NegativeAncestryWitnessIdV1 {
    /// Existing case-9 assumption Lift over the canonical statement.
    Case9AssumptionLift,
    /// Existing case-9 final Resolve over the canonical statement.
    Case9FinalResolve,
    /// New assumption Lift over the exact alternate statement.
    AlternateStatementAssumptionLift,
    /// New Lift from the one bound alternate guest ELF.
    AlternateProgramLift,
    /// New final Resolve over the exact alternate statement.
    AlternateStatementFinalResolve,
    /// New final Join over the exact alternate statement.
    AlternateStatementFinalJoin,
    /// New consumer-program Lift with the same assumption recorded twice.
    DuplicateAssumptionLift,
}

/// Exact first public rejection boundary expected after authentication.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct B4NegativeAncestryFirstPublicRejectionV1 {
    /// Stable public rejection class.
    pub class: String,
    /// Stable first rejection stage within that class.
    pub stage: String,
}

#[derive(Clone, Copy)]
enum CompiledRejection {
    ClaimEdge,
    ResolveExplicit,
    ResolveZeroRoot,
    AssumptionInventory,
}

/// One compiled slot, including physical producer custody and logical replay placement.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct B4NegativeAncestryWitnessLayoutV1 {
    /// Zero-based expanded-corpus row.
    pub expanded_row: u16,
    /// Exact canonical plan execution ID.
    pub execution_id: String,
    /// Recursive positive family used as the semantic base.
    pub base_family: RecursiveAncestryFamily,
    /// Exact receipt witness, shared where several rows copy the same bytes.
    pub witness_id: B4NegativeAncestryWitnessIdV1,
    /// Producer circuit role.
    pub producer_role: B4NegativeAncestryProducerRoleV1,
    /// Logical consumer placement.
    pub logical_placement: B4NegativeAncestryLogicalPlacementV1,
    /// Exact producer recipe.
    pub recipe: B4NegativeAncestryWitnessRecipeV1,
    /// Derived positive-family logical slot.
    pub logical_consumer_path: String,
    /// Create-only physical raw-seal target.
    pub raw_seal_path: String,
    /// Create-only physical receipt-oracle target.
    pub receipt_oracle_path: String,
    /// Exact first public rejection.
    pub first_public_rejection: B4NegativeAncestryFirstPublicRejectionV1,
}

#[derive(Clone, Copy)]
struct CompiledSlot {
    expanded_row: u16,
    execution_id: &'static str,
    base_family: RecursiveAncestryFamily,
    witness_id: B4NegativeAncestryWitnessIdV1,
    producer_role: B4NegativeAncestryProducerRoleV1,
    logical_placement: B4NegativeAncestryLogicalPlacementV1,
    rejection: CompiledRejection,
}

const COMPILED_SLOTS: [CompiledSlot; B4_NEGATIVE_ANCESTRY_BINDING_COUNT] = [
    slot(
        141,
        "claim-edge-family-sweep--terminal-join",
        RecursiveAncestryFamily::TerminalJoin,
        B4NegativeAncestryWitnessIdV1::Case9AssumptionLift,
        B4NegativeAncestryProducerRoleV1::Lift,
        B4NegativeAncestryLogicalPlacementV1::Step0,
        CompiledRejection::ClaimEdge,
    ),
    slot(
        142,
        "claim-edge-family-sweep--terminal-resolve-explicit-root",
        RecursiveAncestryFamily::TerminalResolve,
        B4NegativeAncestryWitnessIdV1::Case9AssumptionLift,
        B4NegativeAncestryProducerRoleV1::Lift,
        B4NegativeAncestryLogicalPlacementV1::Step0,
        CompiledRejection::ClaimEdge,
    ),
    slot(
        143,
        "claim-edge-family-sweep--resolve-zero-root-then-join",
        RecursiveAncestryFamily::ResolveThenJoin,
        B4NegativeAncestryWitnessIdV1::Case9FinalResolve,
        B4NegativeAncestryProducerRoleV1::Resolve,
        B4NegativeAncestryLogicalPlacementV1::Step2,
        CompiledRejection::ClaimEdge,
    ),
    slot(
        145,
        "resolve-explicit-field-sweep--assumption-claim",
        RecursiveAncestryFamily::TerminalResolve,
        B4NegativeAncestryWitnessIdV1::AlternateStatementAssumptionLift,
        B4NegativeAncestryProducerRoleV1::AssumptionLift,
        B4NegativeAncestryLogicalPlacementV1::AssumptionReceipt,
        CompiledRejection::ResolveExplicit,
    ),
    slot(
        147,
        "resolve-explicit-field-sweep--program-id",
        RecursiveAncestryFamily::TerminalResolve,
        B4NegativeAncestryWitnessIdV1::AlternateProgramLift,
        B4NegativeAncestryProducerRoleV1::Lift,
        B4NegativeAncestryLogicalPlacementV1::Step0,
        CompiledRejection::ResolveExplicit,
    ),
    slot(
        148,
        "resolve-explicit-field-sweep--final-claim",
        RecursiveAncestryFamily::TerminalResolve,
        B4NegativeAncestryWitnessIdV1::AlternateStatementFinalResolve,
        B4NegativeAncestryProducerRoleV1::Resolve,
        B4NegativeAncestryLogicalPlacementV1::FinalReceipt,
        CompiledRejection::ResolveExplicit,
    ),
    slot(
        150,
        "resolve-zero-root-field-sweep--assumption-claim",
        RecursiveAncestryFamily::ResolveThenJoin,
        B4NegativeAncestryWitnessIdV1::AlternateStatementAssumptionLift,
        B4NegativeAncestryProducerRoleV1::AssumptionLift,
        B4NegativeAncestryLogicalPlacementV1::AssumptionReceipt,
        CompiledRejection::ResolveZeroRoot,
    ),
    slot(
        151,
        "resolve-zero-root-field-sweep--program-id",
        RecursiveAncestryFamily::ResolveThenJoin,
        B4NegativeAncestryWitnessIdV1::AlternateProgramLift,
        B4NegativeAncestryProducerRoleV1::Lift,
        B4NegativeAncestryLogicalPlacementV1::Step0,
        CompiledRejection::ResolveZeroRoot,
    ),
    slot(
        152,
        "resolve-zero-root-field-sweep--final-claim",
        RecursiveAncestryFamily::ResolveThenJoin,
        B4NegativeAncestryWitnessIdV1::AlternateStatementFinalJoin,
        B4NegativeAncestryProducerRoleV1::Join,
        B4NegativeAncestryLogicalPlacementV1::FinalReceipt,
        CompiledRejection::ResolveZeroRoot,
    ),
    slot(
        153,
        "resolve-assumption-inventory-sweep--missing-assumption",
        RecursiveAncestryFamily::TerminalResolve,
        B4NegativeAncestryWitnessIdV1::Case9AssumptionLift,
        B4NegativeAncestryProducerRoleV1::Lift,
        B4NegativeAncestryLogicalPlacementV1::Step0,
        CompiledRejection::AssumptionInventory,
    ),
    slot(
        154,
        "resolve-assumption-inventory-sweep--extra-assumption",
        RecursiveAncestryFamily::TerminalResolve,
        B4NegativeAncestryWitnessIdV1::DuplicateAssumptionLift,
        B4NegativeAncestryProducerRoleV1::Lift,
        B4NegativeAncestryLogicalPlacementV1::Step0,
        CompiledRejection::AssumptionInventory,
    ),
];

#[allow(
    clippy::too_many_arguments,
    reason = "each argument is one independently reviewed column of the closed eleven-row table"
)]
const fn slot(
    expanded_row: u16,
    execution_id: &'static str,
    base_family: RecursiveAncestryFamily,
    witness_id: B4NegativeAncestryWitnessIdV1,
    producer_role: B4NegativeAncestryProducerRoleV1,
    logical_placement: B4NegativeAncestryLogicalPlacementV1,
    rejection: CompiledRejection,
) -> CompiledSlot {
    CompiledSlot {
        expanded_row,
        execution_id,
        base_family,
        witness_id,
        producer_role,
        logical_placement,
        rejection,
    }
}

/// Materialize and cross-check the exact eleven-slot compiled layout.
///
/// # Errors
///
/// Returns an error if the closed negative plan or recursive path authority
/// has drifted from the compiled slot contract.
pub fn compiled_negative_ancestry_witness_layout() -> Result<Vec<B4NegativeAncestryWitnessLayoutV1>>
{
    let plan = Eip0045B4NegativePlanV1::canonical()?;
    let executions = plan
        .groups
        .iter()
        .flat_map(|group| group.executions.iter())
        .collect::<Vec<_>>();
    COMPILED_SLOTS
        .iter()
        .map(|compiled| {
            let execution = executions
                .get(usize::from(compiled.expanded_row))
                .context("negative ancestry row is outside the closed plan")?;
            ensure!(
                execution.execution_id == compiled.execution_id,
                "negative ancestry execution ID drifted from the closed plan"
            );
            ensure!(
                execution.execution_surface == B4NegativeExecutionSurface::AncestryReplay
                    && execution.qa_result_code == qa_result_code(compiled.rejection),
                "negative ancestry execution surface or public rejection drifted"
            );
            let logical_consumer_path =
                logical_consumer_path(compiled.base_family, compiled.logical_placement)?;
            let recipe = negative_ancestry_witness_recipe(compiled.execution_id)
                .context("negative ancestry execution is absent from the central recipe table")?;
            Ok(B4NegativeAncestryWitnessLayoutV1 {
                expanded_row: compiled.expanded_row,
                execution_id: compiled.execution_id.to_owned(),
                base_family: compiled.base_family,
                witness_id: compiled.witness_id,
                producer_role: compiled.producer_role,
                logical_placement: compiled.logical_placement,
                recipe,
                logical_consumer_path,
                raw_seal_path: format!(
                    "{B4_NEGATIVE_ANCESTRY_WITNESS_ROOT}/{}.raw-seal.bin",
                    compiled.expanded_row
                ),
                receipt_oracle_path: format!(
                    "{B4_NEGATIVE_ANCESTRY_WITNESS_ROOT}/{}.receipt-oracle.bincode",
                    compiled.expanded_row
                ),
                first_public_rejection: rejection_boundary(compiled.rejection),
            })
        })
        .collect()
}

/// Materialize and validate the exact ordered publication inventory.
///
/// # Errors
///
/// Returns an error if any compiled path is non-portable, non-normalized,
/// absolute, escaping, or duplicated.
pub fn compiled_negative_ancestry_publication_paths()
-> Result<[String; B4_NEGATIVE_ANCESTRY_PUBLICATION_FILE_COUNT]> {
    let mut paths = Vec::with_capacity(B4_NEGATIVE_ANCESTRY_PUBLICATION_FILE_COUNT);
    paths.push(B4_NEGATIVE_ANCESTRY_WITNESS_CATALOG_PATH.to_owned());
    paths.push(B4_NEGATIVE_ANCESTRY_ALTERNATE_GUEST_ELF_PATH.to_owned());
    for slot in compiled_negative_ancestry_witness_layout()? {
        paths.push(slot.raw_seal_path);
        paths.push(slot.receipt_oracle_path);
    }

    let mut unique = BTreeSet::new();
    for path in &paths {
        validate_safe_relative_path(path)
            .with_context(|| format!("invalid negative-ancestry publication path {path}"))?;
        ensure!(
            unique.insert(path.as_str()),
            "duplicate negative-ancestry publication path {path}"
        );
    }
    paths.try_into().map_err(|paths: Vec<String>| {
        anyhow::anyhow!(
            "negative-ancestry publication inventory has {} files instead of {}",
            paths.len(),
            B4_NEGATIVE_ANCESTRY_PUBLICATION_FILE_COUNT
        )
    })
}

const fn qa_result_code(rejection: CompiledRejection) -> B4NegativeQaResultCode {
    match rejection {
        CompiledRejection::ClaimEdge => B4NegativeQaResultCode::B4AncestryClaimEdgeMismatch,
        CompiledRejection::ResolveExplicit => {
            B4NegativeQaResultCode::B4ResolveExplicitSemanticsMismatch
        }
        CompiledRejection::ResolveZeroRoot => {
            B4NegativeQaResultCode::B4ResolveZeroRootSemanticsMismatch
        }
        CompiledRejection::AssumptionInventory => {
            B4NegativeQaResultCode::B4ResolveAssumptionInventoryInvalid
        }
    }
}

fn rejection_boundary(rejection: CompiledRejection) -> B4NegativeAncestryFirstPublicRejectionV1 {
    let stage = match rejection {
        CompiledRejection::ClaimEdge => "claim-edge",
        CompiledRejection::ResolveExplicit => "resolve-explicit-semantics",
        CompiledRejection::ResolveZeroRoot => "resolve-zero-root-semantics",
        CompiledRejection::AssumptionInventory => "resolve-assumption-inventory",
    };
    B4NegativeAncestryFirstPublicRejectionV1 {
        class: "ancestry-replay-mismatch".to_owned(),
        stage: stage.to_owned(),
    }
}

fn logical_consumer_path(
    family: RecursiveAncestryFamily,
    placement: B4NegativeAncestryLogicalPlacementV1,
) -> Result<String> {
    if placement == B4NegativeAncestryLogicalPlacementV1::FinalReceipt {
        return Ok(recursive_ancestry_case_path(
            family,
            RECURSIVE_ANCESTRY_FINAL_SEAL_FILE,
        ));
    }
    let suffix = match placement {
        B4NegativeAncestryLogicalPlacementV1::AssumptionReceipt => {
            "candidate-ancestry-assumption-raw-seal.bin"
        }
        B4NegativeAncestryLogicalPlacementV1::Step0 => "candidate-ancestry-step-00-raw-seal.bin",
        B4NegativeAncestryLogicalPlacementV1::Step2 => "candidate-ancestry-step-02-raw-seal.bin",
        B4NegativeAncestryLogicalPlacementV1::FinalReceipt => unreachable!(),
    };
    recursive_ancestry_expected_auxiliary_paths(family)
        .into_iter()
        .find(|path| path.ends_with(suffix))
        .context("logical ancestry placement is absent from the compiled path authority")
}

/// One measured post-generation witness identity.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct B4NegativeAncestryWitnessEntryV1 {
    /// Zero-based expanded-corpus row.
    pub expanded_row: u16,
    /// Exact closed negative-plan execution ID.
    pub execution_id: String,
    /// Recursive semantic base.
    pub base_family: RecursiveAncestryFamily,
    /// Cryptographically distinct witness identity.
    pub witness_id: B4NegativeAncestryWitnessIdV1,
    /// Producer circuit role.
    pub producer_role: B4NegativeAncestryProducerRoleV1,
    /// Logical ancestry placement.
    pub logical_placement: B4NegativeAncestryLogicalPlacementV1,
    /// Closed producer recipe.
    pub recipe: B4NegativeAncestryWitnessRecipeV1,
    /// Path derived from the recursive ancestry authority.
    pub logical_consumer_path: String,
    /// Exact first public semantic rejection.
    pub first_public_rejection: B4NegativeAncestryFirstPublicRejectionV1,
    /// Complete shared receipt-claim projection.
    pub claim: RecursiveAncestryClaim,
    /// Independently recomputed RISC Zero receipt-claim digest.
    pub claim_digest: String,
    /// Program which produced this receipt.
    pub producer_program_id: String,
    /// Exact typed terminal.
    pub terminal: RecursiveAncestryTerminal,
    /// Cryptographically authenticated producer control root.
    pub control_root: String,
    /// Measured create-only raw-seal artifact.
    pub raw_seal: B4ContractArtifactIdentityV1,
    /// Measured create-only receipt-oracle artifact.
    pub receipt_oracle: B4ContractArtifactIdentityV1,
}

/// Post-generation candidate catalogue. Validation is structural, not authority.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct Eip0045B4NegativeAncestryWitnessCatalogV1 {
    /// Exact format discriminator.
    pub format: String,
    /// Exact schema version.
    pub format_version: u8,
    /// Closed post-generation stage.
    pub stage: B4NegativeAncestryWitnessCatalogStageV1,
    /// Exact non-selectable codec used by every direct receipt oracle.
    pub receipt_oracle_codec: String,
    /// Exact campaign negative-plan identity.
    pub negative_plan: B4ContractArtifactIdentityV1,
    /// Exact binary profile-manifest identity.
    pub profile_manifest: B4ContractArtifactIdentityV1,
    /// Exact ELF used only by the two different-program Lift witnesses.
    pub alternate_guest_elf: B4ContractArtifactIdentityV1,
    /// Consumer guest program ID.
    pub consumer_program_id: String,
    /// Image ID later recomputed from `alternateGuestElf`.
    pub alternate_program_id: String,
    /// Profile inner control root.
    pub inner_control_root: String,
    /// Exact ordered eleven-row binding inventory.
    pub entries: Vec<B4NegativeAncestryWitnessEntryV1>,
}

impl Eip0045B4NegativeAncestryWitnessCatalogV1 {
    /// Parse and validate exact RFC 8785 JCS.
    ///
    /// # Errors
    ///
    /// Returns an error for malformed, oversized, duplicate-key,
    /// non-canonical, unknown-field, or semantically drifted input.
    pub fn from_canonical_jcs(source: &[u8]) -> Result<Self> {
        ensure!(
            source.len() <= MAX_CATALOG_JCS_BYTES,
            "negative ancestry witness catalogue exceeds its JCS bound"
        );
        let value = validate_canonical_json_source(source)
            .context("negative ancestry witness catalogue is not exact RFC 8785 JCS")?;
        let catalog: Self =
            serde_json::from_value(value).context("invalid negative ancestry catalogue shape")?;
        catalog.validate()?;
        ensure!(
            catalog.to_canonical_jcs()? == source,
            "negative ancestry witness catalogue does not round-trip byte-exactly"
        );
        Ok(catalog)
    }

    /// Serialize the validated candidate as exact RFC 8785 JCS.
    ///
    /// # Errors
    ///
    /// Returns an error if the candidate is invalid or exceeds its bound.
    pub fn to_canonical_jcs(&self) -> Result<Vec<u8>> {
        self.validate()?;
        let value =
            serde_json::to_value(self).context("cannot serialize negative ancestry catalogue")?;
        let bytes = canonical_json_bytes(&value)?;
        ensure!(
            bytes.len() <= MAX_CATALOG_JCS_BYTES,
            "negative ancestry witness catalogue exceeds its JCS bound"
        );
        Ok(bytes)
    }

    /// Validate the closed structural catalogue without conferring authority.
    ///
    /// # Errors
    ///
    /// Returns an error for any top-level identity, slot, claim, program,
    /// terminal, path, length, digest, encoding, order, or cardinality drift.
    pub fn validate(&self) -> Result<()> {
        ensure!(
            self.format == B4_NEGATIVE_ANCESTRY_WITNESS_CATALOG_FORMAT,
            "wrong negative ancestry witness catalogue format"
        );
        ensure!(
            self.format_version == B4_NEGATIVE_ANCESTRY_WITNESS_CATALOG_VERSION,
            "wrong negative ancestry witness catalogue version"
        );
        ensure!(
            self.stage == B4NegativeAncestryWitnessCatalogStageV1::PostGenerationDerived,
            "wrong negative ancestry witness catalogue stage"
        );
        ensure!(
            self.receipt_oracle_codec == RECEIPT_ORACLE_CODEC_V1,
            "wrong negative ancestry receipt-oracle codec"
        );
        validate_top_level_identity(
            &self.negative_plan,
            B4_NEGATIVE_ANCESTRY_PLAN_PATH,
            B4ContractArtifactEncodingV1::Rfc8785Jcs,
            None,
            "negative plan",
        )?;
        ensure!(
            self.negative_plan.byte_length <= MAX_NEGATIVE_PLAN_BYTES,
            "negative plan exceeds its role-specific byte bound"
        );
        validate_top_level_identity(
            &self.profile_manifest,
            B4_NEGATIVE_ANCESTRY_PROFILE_MANIFEST_PATH,
            B4ContractArtifactEncodingV1::RawBytes,
            Some(MANIFEST_BYTES as u64),
            "profile manifest",
        )?;
        validate_top_level_identity(
            &self.alternate_guest_elf,
            B4_NEGATIVE_ANCESTRY_ALTERNATE_GUEST_ELF_PATH,
            B4ContractArtifactEncodingV1::RawBytes,
            None,
            "alternate guest ELF",
        )?;
        ensure!(
            self.alternate_guest_elf.byte_length <= MAX_ALTERNATE_GUEST_ELF_BYTES,
            "alternate guest ELF exceeds its role-specific byte bound"
        );
        validate_lower_hex_exact(&self.consumer_program_id, DIGEST_BYTES)
            .context("consumer program ID is not exact lowercase hex32")?;
        validate_lower_hex_exact(&self.alternate_program_id, DIGEST_BYTES)
            .context("alternate program ID is not exact lowercase hex32")?;
        ensure!(
            self.alternate_program_id != self.consumer_program_id,
            "alternate program ID equals the consumer program ID"
        );
        validate_lower_hex_exact(&self.inner_control_root, DIGEST_BYTES)
            .context("inner control root is not exact lowercase hex32")?;
        ensure!(
            self.inner_control_root == RISC0_INNER_CONTROL_ROOT_HEX,
            "inner control root differs from the closed profile"
        );

        let layout = compiled_negative_ancestry_witness_layout()?;
        ensure!(
            self.entries.len() == B4_NEGATIVE_ANCESTRY_BINDING_COUNT,
            "negative ancestry witness catalogue must contain exactly eleven row bindings"
        );
        let mut physical_paths = BTreeSet::from([self.alternate_guest_elf.path.as_str()]);
        let mut witness_ids = BTreeSet::new();
        for (entry, expected) in self.entries.iter().zip(&layout) {
            validate_entry(
                entry,
                expected,
                &self.consumer_program_id,
                &self.alternate_program_id,
                &self.inner_control_root,
            )?;
            witness_ids.insert(entry.witness_id);
            ensure!(
                physical_paths.insert(entry.raw_seal.path.as_str())
                    && physical_paths.insert(entry.receipt_oracle.path.as_str()),
                "negative ancestry physical source paths must be globally unique"
            );
        }
        ensure!(
            witness_ids.len() == B4_NEGATIVE_ANCESTRY_DISTINCT_WITNESS_COUNT,
            "negative ancestry row bindings do not select exactly seven witnesses"
        );
        validate_cross_binding_evidence(&self.entries)?;
        Ok(())
    }
}

fn validate_top_level_identity(
    identity: &B4ContractArtifactIdentityV1,
    path: &str,
    encoding: B4ContractArtifactEncodingV1,
    exact_length: Option<u64>,
    label: &str,
) -> Result<()> {
    identity
        .validate()
        .with_context(|| format!("invalid {label} identity"))?;
    ensure!(identity.path == path, "{label} path drifted");
    ensure!(identity.encoding == encoding, "{label} encoding drifted");
    if let Some(exact_length) = exact_length {
        ensure!(
            identity.byte_length == exact_length,
            "{label} length drifted"
        );
    }
    Ok(())
}

#[allow(
    clippy::too_many_lines,
    reason = "the validation sequence mirrors every independently falsifiable catalogue field"
)]
fn validate_entry(
    entry: &B4NegativeAncestryWitnessEntryV1,
    expected: &B4NegativeAncestryWitnessLayoutV1,
    consumer_program_id: &str,
    alternate_program_id: &str,
    inner_control_root: &str,
) -> Result<()> {
    ensure!(
        entry.expanded_row == expected.expanded_row
            && entry.execution_id == expected.execution_id
            && entry.base_family == expected.base_family
            && entry.witness_id == expected.witness_id
            && entry.producer_role == expected.producer_role
            && entry.logical_placement == expected.logical_placement
            && entry.recipe == expected.recipe
            && entry.logical_consumer_path == expected.logical_consumer_path
            && entry.first_public_rejection == expected.first_public_rejection,
        "negative ancestry witness entry drifted from its compiled slot"
    );
    entry
        .raw_seal
        .validate()
        .context("invalid negative ancestry raw-seal identity")?;
    entry
        .receipt_oracle
        .validate()
        .context("invalid negative ancestry receipt-oracle identity")?;
    ensure!(
        entry.raw_seal.path == expected.raw_seal_path
            && entry.raw_seal.encoding == B4ContractArtifactEncodingV1::RawBytes
            && entry.raw_seal.byte_length == PROOF_BYTES as u64,
        "negative ancestry raw-seal path, encoding, or length drifted"
    );
    ensure!(
        entry.receipt_oracle.path == expected.receipt_oracle_path
            && entry.receipt_oracle.encoding == B4ContractArtifactEncodingV1::RawBytes
            && (1..=RECEIPT_ORACLE_MAX_BYTES_U64).contains(&entry.receipt_oracle.byte_length),
        "negative ancestry receipt-oracle path, encoding, or length drifted"
    );
    ensure!(
        entry.raw_seal.path != entry.receipt_oracle.path
            && entry.raw_seal.path != entry.logical_consumer_path
            && entry.receipt_oracle.path != entry.logical_consumer_path,
        "negative ancestry physical source path aliases a logical consumer slot"
    );
    validate_lower_hex_exact(&entry.producer_program_id, DIGEST_BYTES)
        .context("producer program ID is not exact lowercase hex32")?;
    ensure!(
        entry.claim.pre_state_digest == entry.producer_program_id,
        "producer program ID is not bound by the projected claim pre-state"
    );
    let expected_producer_program = if matches!(entry.expanded_row, 147 | 151) {
        alternate_program_id
    } else {
        consumer_program_id
    };
    ensure!(
        entry.producer_program_id == expected_producer_program,
        "producer program differs from the closed row binding"
    );
    validate_lower_hex_exact(&entry.claim_digest, DIGEST_BYTES)
        .context("claim digest is not exact lowercase hex32")?;
    ensure!(
        hex::encode(recursive_ancestry_claim_digest(&entry.claim)?) == entry.claim_digest,
        "claim digest differs from independent RISC Zero recomputation"
    );
    ensure!(
        entry.control_root == inner_control_root,
        "producer control root differs from the catalogued profile root"
    );
    ensure!(
        entry.terminal == expected_terminal(expected.witness_id, expected.producer_role)?,
        "typed producer terminal differs from the compiled role"
    );
    Ok(())
}

fn validate_cross_binding_evidence(entries: &[B4NegativeAncestryWitnessEntryV1]) -> Result<()> {
    let [
        row_141,
        row_142,
        row_143,
        row_145,
        row_147,
        row_148,
        row_150,
        row_151,
        row_152,
        row_153,
        row_154,
    ] = entries
    else {
        bail!("negative ancestry witness relationship check requires eleven row bindings");
    };

    for (left, right) in [
        (row_141, row_142),
        (row_141, row_153),
        (row_145, row_150),
        (row_147, row_151),
    ] {
        ensure!(
            same_evidence_except_paths(left, right),
            "aliased negative ancestry rows do not bind the same receipt evidence"
        );
    }
    ensure!(
        same_claim(row_141, row_143),
        "canonical assumption Lift and final Resolve do not authenticate the same claim"
    );
    for other in [row_148, row_150, row_152] {
        ensure!(
            same_claim(row_145, other),
            "alternate-statement receipts do not authenticate the same claim"
        );
    }
    ensure!(
        !same_claim(row_141, row_145),
        "alternate statement did not change the authenticated claim"
    );
    ensure!(
        !same_claim(row_141, row_154),
        "duplicate-assumption Lift did not change the authenticated claim"
    );
    ensure!(
        !same_claim(row_145, row_154),
        "duplicate-assumption Lift aliases the alternate-statement claim"
    );

    let representatives = [
        row_141, row_143, row_145, row_147, row_148, row_152, row_154,
    ];
    let mut raw_seal_digests = BTreeSet::new();
    let mut receipt_oracle_digests = BTreeSet::new();
    for representative in representatives {
        ensure!(
            raw_seal_digests.insert(representative.raw_seal.sha256.as_str()),
            "distinct witness IDs alias one raw-seal digest"
        );
        ensure!(
            receipt_oracle_digests.insert(representative.receipt_oracle.sha256.as_str()),
            "distinct witness IDs alias one receipt-oracle digest"
        );
    }
    Ok(())
}

fn same_evidence_except_paths(
    left: &B4NegativeAncestryWitnessEntryV1,
    right: &B4NegativeAncestryWitnessEntryV1,
) -> bool {
    same_claim(left, right)
        && left.producer_program_id == right.producer_program_id
        && left.terminal == right.terminal
        && left.control_root == right.control_root
        && same_artifact_bytes(&left.raw_seal, &right.raw_seal)
        && same_artifact_bytes(&left.receipt_oracle, &right.receipt_oracle)
}

fn same_claim(
    left: &B4NegativeAncestryWitnessEntryV1,
    right: &B4NegativeAncestryWitnessEntryV1,
) -> bool {
    left.claim == right.claim && left.claim_digest == right.claim_digest
}

fn same_artifact_bytes(
    left: &B4ContractArtifactIdentityV1,
    right: &B4ContractArtifactIdentityV1,
) -> bool {
    left.byte_length == right.byte_length
        && left.sha256 == right.sha256
        && left.encoding == right.encoding
}

/// Return the sole typed stock terminal admitted for one compiled witness and role.
pub(crate) fn expected_terminal(
    witness_id: B4NegativeAncestryWitnessIdV1,
    role: B4NegativeAncestryProducerRoleV1,
) -> Result<RecursiveAncestryTerminal> {
    let terminal = match (witness_id, role) {
        (
            B4NegativeAncestryWitnessIdV1::DuplicateAssumptionLift,
            B4NegativeAncestryProducerRoleV1::Lift,
        ) => RecursiveAncestryTerminal::Lift {
            segment_po2: 16,
            control_id: RISC0_NORMAL_LIFT_CONTROL_IDS_HEX[1].to_owned(),
        },
        (
            B4NegativeAncestryWitnessIdV1::Case9AssumptionLift
            | B4NegativeAncestryWitnessIdV1::AlternateProgramLift,
            B4NegativeAncestryProducerRoleV1::Lift,
        )
        | (
            B4NegativeAncestryWitnessIdV1::AlternateStatementAssumptionLift,
            B4NegativeAncestryProducerRoleV1::AssumptionLift,
        ) => RecursiveAncestryTerminal::Lift {
            segment_po2: 15,
            control_id: RISC0_NORMAL_LIFT_CONTROL_IDS_HEX[0].to_owned(),
        },
        (
            B4NegativeAncestryWitnessIdV1::AlternateStatementFinalJoin,
            B4NegativeAncestryProducerRoleV1::Join,
        ) => RecursiveAncestryTerminal::Join {
            control_id: RISC0_JOIN_CONTROL_ID_HEX.to_owned(),
        },
        (
            B4NegativeAncestryWitnessIdV1::Case9FinalResolve
            | B4NegativeAncestryWitnessIdV1::AlternateStatementFinalResolve,
            B4NegativeAncestryProducerRoleV1::Resolve,
        ) => RecursiveAncestryTerminal::Resolve {
            control_id: RISC0_RESOLVE_CONTROL_ID_HEX.to_owned(),
        },
        _ => bail!("negative ancestry witness {witness_id:?} cannot use producer role {role:?}"),
    };
    Ok(terminal)
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use serde_json::{Value, json};

    use super::*;
    use crate::{
        b4_campaign_contract::{B4ContractArtifactEncodingV1, B4ContractArtifactIdentityV1},
        canonical::canonical_json_bytes,
        constants::{
            DIGEST_BYTES, MANIFEST_BYTES, PROOF_BYTES, RISC0_INNER_CONTROL_ROOT_HEX,
            RISC0_NORMAL_LIFT_CONTROL_IDS_HEX,
        },
        recursive_ancestry::{
            RecursiveAncestryClaim, RecursiveAncestryTerminal, recursive_ancestry_claim_digest,
        },
    };

    fn identity(
        path: &str,
        encoding: B4ContractArtifactEncodingV1,
        bytes: &[u8],
    ) -> B4ContractArtifactIdentityV1 {
        B4ContractArtifactIdentityV1::from_bytes(path, encoding, bytes).unwrap()
    }

    #[test]
    fn publication_inventory_is_exactly_twenty_four_safe_unique_paths() {
        let paths = compiled_negative_ancestry_publication_paths().unwrap();
        let expected = [
            "reproduction/negative-ancestry-witness-catalog.json",
            "reproduction/negative-ancestry-witnesses/alternate-program-guest.elf",
            "reproduction/negative-ancestry-witnesses/141.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/141.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/142.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/142.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/143.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/143.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/145.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/145.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/147.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/147.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/148.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/148.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/150.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/150.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/151.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/151.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/152.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/152.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/153.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/153.receipt-oracle.bincode",
            "reproduction/negative-ancestry-witnesses/154.raw-seal.bin",
            "reproduction/negative-ancestry-witnesses/154.receipt-oracle.bincode",
        ];

        assert_eq!(B4_NEGATIVE_ANCESTRY_PUBLICATION_FILE_COUNT, expected.len());
        assert_eq!(paths.each_ref().map(String::as_str), expected);
        assert_eq!(
            paths.iter().collect::<BTreeSet<_>>().len(),
            B4_NEGATIVE_ANCESTRY_PUBLICATION_FILE_COUNT
        );
        assert!(paths.iter().all(|path| path.starts_with("reproduction/")));
    }

    fn claim(program_id: &str, seed: u8) -> RecursiveAncestryClaim {
        RecursiveAncestryClaim {
            input_digest: format!("{seed:02x}").repeat(DIGEST_BYTES),
            pre_state_digest: program_id.to_owned(),
            post_state_digest: format!("{:02x}", seed.wrapping_add(1)).repeat(DIGEST_BYTES),
            system_exit: 0,
            user_exit: 0,
            output_digest: format!("{:02x}", seed.wrapping_add(2)).repeat(DIGEST_BYTES),
        }
    }

    fn terminal(
        witness_id: B4NegativeAncestryWitnessIdV1,
        role: B4NegativeAncestryProducerRoleV1,
    ) -> RecursiveAncestryTerminal {
        expected_terminal(witness_id, role).unwrap()
    }

    const fn witness_artifact_seed(witness_id: B4NegativeAncestryWitnessIdV1) -> u8 {
        match witness_id {
            B4NegativeAncestryWitnessIdV1::Case9AssumptionLift => 1,
            B4NegativeAncestryWitnessIdV1::Case9FinalResolve => 2,
            B4NegativeAncestryWitnessIdV1::AlternateStatementAssumptionLift => 3,
            B4NegativeAncestryWitnessIdV1::AlternateProgramLift => 4,
            B4NegativeAncestryWitnessIdV1::AlternateStatementFinalResolve => 5,
            B4NegativeAncestryWitnessIdV1::AlternateStatementFinalJoin => 6,
            B4NegativeAncestryWitnessIdV1::DuplicateAssumptionLift => 7,
        }
    }

    const fn witness_claim_seed(witness_id: B4NegativeAncestryWitnessIdV1) -> u8 {
        match witness_id {
            B4NegativeAncestryWitnessIdV1::Case9AssumptionLift
            | B4NegativeAncestryWitnessIdV1::Case9FinalResolve => 1,
            B4NegativeAncestryWitnessIdV1::AlternateStatementAssumptionLift
            | B4NegativeAncestryWitnessIdV1::AlternateStatementFinalResolve
            | B4NegativeAncestryWitnessIdV1::AlternateStatementFinalJoin => 2,
            B4NegativeAncestryWitnessIdV1::AlternateProgramLift => 3,
            B4NegativeAncestryWitnessIdV1::DuplicateAssumptionLift => 4,
        }
    }

    #[test]
    fn duplicate_assumption_lift_uses_po2_16_while_other_lifts_remain_po2_15() {
        assert_eq!(
            expected_terminal(
                B4NegativeAncestryWitnessIdV1::DuplicateAssumptionLift,
                B4NegativeAncestryProducerRoleV1::Lift,
            )
            .unwrap(),
            RecursiveAncestryTerminal::Lift {
                segment_po2: 16,
                control_id: RISC0_NORMAL_LIFT_CONTROL_IDS_HEX[1].to_owned(),
            }
        );

        for (witness_id, role) in [
            (
                B4NegativeAncestryWitnessIdV1::Case9AssumptionLift,
                B4NegativeAncestryProducerRoleV1::Lift,
            ),
            (
                B4NegativeAncestryWitnessIdV1::AlternateStatementAssumptionLift,
                B4NegativeAncestryProducerRoleV1::AssumptionLift,
            ),
            (
                B4NegativeAncestryWitnessIdV1::AlternateProgramLift,
                B4NegativeAncestryProducerRoleV1::Lift,
            ),
        ] {
            assert_eq!(
                expected_terminal(witness_id, role).unwrap(),
                RecursiveAncestryTerminal::Lift {
                    segment_po2: 15,
                    control_id: RISC0_NORMAL_LIFT_CONTROL_IDS_HEX[0].to_owned(),
                }
            );
        }
    }

    #[test]
    fn terminal_dispatch_rejects_every_impossible_witness_role_pair() {
        let witness_ids = [
            B4NegativeAncestryWitnessIdV1::Case9AssumptionLift,
            B4NegativeAncestryWitnessIdV1::Case9FinalResolve,
            B4NegativeAncestryWitnessIdV1::AlternateStatementAssumptionLift,
            B4NegativeAncestryWitnessIdV1::AlternateProgramLift,
            B4NegativeAncestryWitnessIdV1::AlternateStatementFinalResolve,
            B4NegativeAncestryWitnessIdV1::AlternateStatementFinalJoin,
            B4NegativeAncestryWitnessIdV1::DuplicateAssumptionLift,
        ];
        let roles = [
            B4NegativeAncestryProducerRoleV1::Lift,
            B4NegativeAncestryProducerRoleV1::AssumptionLift,
            B4NegativeAncestryProducerRoleV1::Join,
            B4NegativeAncestryProducerRoleV1::Resolve,
        ];
        let valid_pairs = [
            (
                B4NegativeAncestryWitnessIdV1::Case9AssumptionLift,
                B4NegativeAncestryProducerRoleV1::Lift,
            ),
            (
                B4NegativeAncestryWitnessIdV1::Case9FinalResolve,
                B4NegativeAncestryProducerRoleV1::Resolve,
            ),
            (
                B4NegativeAncestryWitnessIdV1::AlternateStatementAssumptionLift,
                B4NegativeAncestryProducerRoleV1::AssumptionLift,
            ),
            (
                B4NegativeAncestryWitnessIdV1::AlternateProgramLift,
                B4NegativeAncestryProducerRoleV1::Lift,
            ),
            (
                B4NegativeAncestryWitnessIdV1::AlternateStatementFinalResolve,
                B4NegativeAncestryProducerRoleV1::Resolve,
            ),
            (
                B4NegativeAncestryWitnessIdV1::AlternateStatementFinalJoin,
                B4NegativeAncestryProducerRoleV1::Join,
            ),
            (
                B4NegativeAncestryWitnessIdV1::DuplicateAssumptionLift,
                B4NegativeAncestryProducerRoleV1::Lift,
            ),
        ];

        for witness_id in witness_ids {
            for role in roles {
                assert_eq!(
                    expected_terminal(witness_id, role).is_ok(),
                    valid_pairs.contains(&(witness_id, role)),
                    "unexpected terminal dispatch for {witness_id:?}/{role:?}"
                );
            }
        }
    }

    fn catalog() -> Eip0045B4NegativeAncestryWitnessCatalogV1 {
        let consumer = "31".repeat(DIGEST_BYTES);
        let alternate = "42".repeat(DIGEST_BYTES);
        let entries = compiled_negative_ancestry_witness_layout()
            .unwrap()
            .into_iter()
            .map(|layout| {
                let producer =
                    if layout.witness_id == B4NegativeAncestryWitnessIdV1::AlternateProgramLift {
                        alternate.clone()
                    } else {
                        consumer.clone()
                    };
                let artifact_seed = witness_artifact_seed(layout.witness_id);
                let claim = claim(&producer, witness_claim_seed(layout.witness_id));
                B4NegativeAncestryWitnessEntryV1 {
                    expanded_row: layout.expanded_row,
                    execution_id: layout.execution_id,
                    base_family: layout.base_family,
                    witness_id: layout.witness_id,
                    producer_role: layout.producer_role,
                    logical_placement: layout.logical_placement,
                    recipe: layout.recipe,
                    logical_consumer_path: layout.logical_consumer_path,
                    first_public_rejection: layout.first_public_rejection,
                    claim_digest: hex::encode(recursive_ancestry_claim_digest(&claim).unwrap()),
                    claim,
                    producer_program_id: producer,
                    terminal: terminal(layout.witness_id, layout.producer_role),
                    control_root: RISC0_INNER_CONTROL_ROOT_HEX.to_owned(),
                    raw_seal: identity(
                        &layout.raw_seal_path,
                        B4ContractArtifactEncodingV1::RawBytes,
                        &vec![artifact_seed; PROOF_BYTES],
                    ),
                    receipt_oracle: identity(
                        &layout.receipt_oracle_path,
                        B4ContractArtifactEncodingV1::RawBytes,
                        &[artifact_seed; 64],
                    ),
                }
            })
            .collect();
        Eip0045B4NegativeAncestryWitnessCatalogV1 {
            format: B4_NEGATIVE_ANCESTRY_WITNESS_CATALOG_FORMAT.to_owned(),
            format_version: B4_NEGATIVE_ANCESTRY_WITNESS_CATALOG_VERSION,
            stage: B4NegativeAncestryWitnessCatalogStageV1::PostGenerationDerived,
            receipt_oracle_codec: RECEIPT_ORACLE_CODEC_V1.to_owned(),
            negative_plan: identity(
                B4_NEGATIVE_ANCESTRY_PLAN_PATH,
                B4ContractArtifactEncodingV1::Rfc8785Jcs,
                b"{\"plan\":1}",
            ),
            profile_manifest: identity(
                B4_NEGATIVE_ANCESTRY_PROFILE_MANIFEST_PATH,
                B4ContractArtifactEncodingV1::RawBytes,
                &vec![0x55; MANIFEST_BYTES],
            ),
            alternate_guest_elf: identity(
                B4_NEGATIVE_ANCESTRY_ALTERNATE_GUEST_ELF_PATH,
                B4ContractArtifactEncodingV1::RawBytes,
                b"synthetic-alternate-guest-elf",
            ),
            consumer_program_id: consumer,
            alternate_program_id: alternate,
            inner_control_root: RISC0_INNER_CONTROL_ROOT_HEX.to_owned(),
            entries,
        }
    }

    #[test]
    fn compiled_layout_is_the_exact_ordered_eleven_row_authority() {
        let layout = compiled_negative_ancestry_witness_layout().unwrap();
        assert_eq!(
            layout
                .iter()
                .map(|slot| slot.expanded_row)
                .collect::<Vec<_>>(),
            [141, 142, 143, 145, 147, 148, 150, 151, 152, 153, 154]
        );
        assert_eq!(
            layout
                .iter()
                .map(|slot| slot.execution_id.as_str())
                .collect::<Vec<_>>(),
            [
                "claim-edge-family-sweep--terminal-join",
                "claim-edge-family-sweep--terminal-resolve-explicit-root",
                "claim-edge-family-sweep--resolve-zero-root-then-join",
                "resolve-explicit-field-sweep--assumption-claim",
                "resolve-explicit-field-sweep--program-id",
                "resolve-explicit-field-sweep--final-claim",
                "resolve-zero-root-field-sweep--assumption-claim",
                "resolve-zero-root-field-sweep--program-id",
                "resolve-zero-root-field-sweep--final-claim",
                "resolve-assumption-inventory-sweep--missing-assumption",
                "resolve-assumption-inventory-sweep--extra-assumption",
            ]
        );
        for excluded in [140, 144, 146, 149, 155] {
            assert!(!layout.iter().any(|slot| slot.expanded_row == excluded));
        }
        assert_eq!(
            layout[0].raw_seal_path,
            "reproduction/negative-ancestry-witnesses/141.raw-seal.bin"
        );
        assert_eq!(
            layout[0].receipt_oracle_path,
            "reproduction/negative-ancestry-witnesses/141.receipt-oracle.bincode"
        );
        for slot in layout {
            assert_ne!(slot.raw_seal_path, slot.receipt_oracle_path);
            assert_ne!(slot.raw_seal_path, slot.logical_consumer_path);
            assert_ne!(slot.receipt_oracle_path, slot.logical_consumer_path);
        }
    }

    #[test]
    fn catalog_round_trips_only_as_strict_bounded_jcs() {
        let catalog = catalog();
        let bytes = catalog.to_canonical_jcs().unwrap();
        assert_eq!(
            Eip0045B4NegativeAncestryWitnessCatalogV1::from_canonical_jcs(&bytes).unwrap(),
            catalog
        );

        let pretty = serde_json::to_vec_pretty(&catalog).unwrap();
        assert!(Eip0045B4NegativeAncestryWitnessCatalogV1::from_canonical_jcs(&pretty).is_err());
        let duplicate = bytes
            .strip_prefix(b"{")
            .map(|tail| {
                [
                    b"{\"format\":\"Eip0045B4NegativeAncestryWitnessCatalogV1\",".as_slice(),
                    tail,
                ]
                .concat()
            })
            .unwrap();
        assert!(Eip0045B4NegativeAncestryWitnessCatalogV1::from_canonical_jcs(&duplicate).is_err());

        let mut unknown = serde_json::to_value(&catalog).unwrap();
        unknown
            .as_object_mut()
            .unwrap()
            .insert("unknown".to_owned(), Value::Bool(true));
        let unknown = canonical_json_bytes(&unknown).unwrap();
        assert!(Eip0045B4NegativeAncestryWitnessCatalogV1::from_canonical_jcs(&unknown).is_err());
    }

    #[test]
    fn catalog_requires_the_exact_frozen_receipt_oracle_codec() {
        const EXPECTED: &str = "bincode-1.3.3-fixint-little-endian-reject-trailing-limit-1048576";

        let value = serde_json::to_value(catalog()).unwrap();
        assert_eq!(
            value
                .get("receiptOracleCodec")
                .and_then(serde_json::Value::as_str),
            Some(EXPECTED)
        );

        let mut missing = value.clone();
        missing
            .as_object_mut()
            .unwrap()
            .remove("receiptOracleCodec");
        let missing = canonical_json_bytes(&missing).unwrap();
        assert!(Eip0045B4NegativeAncestryWitnessCatalogV1::from_canonical_jcs(&missing).is_err());

        let mut wrong = value;
        wrong["receiptOracleCodec"] =
            json!("bincode-1.3.3-varint-big-endian-allow-trailing-limit-unbounded");
        let wrong = canonical_json_bytes(&wrong).unwrap();
        assert!(Eip0045B4NegativeAncestryWitnessCatalogV1::from_canonical_jcs(&wrong).is_err());
    }

    #[test]
    fn schema_requires_the_exact_frozen_receipt_oracle_codec() {
        const EXPECTED: &str = "bincode-1.3.3-fixint-little-endian-reject-trailing-limit-1048576";

        let schema: Value = serde_json::from_str(include_str!(
            "../finalizer-schema/b4-negative-ancestry-witness-catalog-v1.schema.json"
        ))
        .unwrap();
        assert_eq!(
            schema["properties"]["receiptOracleCodec"]["const"],
            EXPECTED
        );
        assert!(
            schema["required"]
                .as_array()
                .unwrap()
                .iter()
                .any(|field| field == "receiptOracleCodec")
        );
    }

    #[test]
    fn public_rejection_is_the_explicit_closed_class_and_stage_pair() {
        let value = serde_json::to_value(catalog()).unwrap();
        assert_eq!(
            value["entries"][0]["firstPublicRejection"],
            json!({
                "class": "ancestry-replay-mismatch",
                "stage": "claim-edge"
            })
        );
    }

    #[test]
    fn each_row_serializes_one_exact_full_producer_recipe() {
        let value = serde_json::to_value(catalog()).unwrap();
        let recipes = value["entries"]
            .as_array()
            .unwrap()
            .iter()
            .map(|entry| entry["recipe"].as_str().unwrap())
            .collect::<Vec<_>>();
        assert_eq!(
            recipes,
            [
                "reuse-case9-assumption-at-terminal-join-step0",
                "reuse-case9-assumption-at-terminal-resolve-step0",
                "reuse-case9-final-resolve-at-resolve-then-join-step2",
                "alternate-statement-assumption-lift-for-terminal-resolve",
                "alternate-guest-lift-for-terminal-resolve",
                "alternate-statement-final-resolve-for-terminal-resolve",
                "alternate-statement-assumption-lift-for-resolve-then-join",
                "alternate-guest-lift-for-resolve-then-join",
                "alternate-statement-final-join-for-resolve-then-join",
                "reuse-case9-assumption-with-empty-inventory",
                "duplicate-assumption-lift-with-duplicated-inventory",
            ]
        );
    }

    #[test]
    fn eleven_rows_map_to_the_exact_seven_witness_identities() {
        let value = serde_json::to_value(catalog()).unwrap();
        let witness_ids = value["entries"]
            .as_array()
            .unwrap()
            .iter()
            .map(|entry| entry["witnessId"].as_str().unwrap_or("<missing>"))
            .collect::<Vec<_>>();
        assert_eq!(
            witness_ids,
            [
                "case9-assumption-lift",
                "case9-assumption-lift",
                "case9-final-resolve",
                "alternate-statement-assumption-lift",
                "alternate-program-lift",
                "alternate-statement-final-resolve",
                "alternate-statement-assumption-lift",
                "alternate-program-lift",
                "alternate-statement-final-join",
                "case9-assumption-lift",
                "duplicate-assumption-lift",
            ]
        );
    }

    #[test]
    fn aliases_share_full_evidence_and_related_terminals_share_exact_claims() {
        fn same_evidence_except_paths(
            left: &B4NegativeAncestryWitnessEntryV1,
            right: &B4NegativeAncestryWitnessEntryV1,
        ) {
            assert_eq!(left.claim, right.claim);
            assert_eq!(left.claim_digest, right.claim_digest);
            assert_eq!(left.producer_program_id, right.producer_program_id);
            assert_eq!(left.terminal, right.terminal);
            assert_eq!(left.control_root, right.control_root);
            assert_eq!(left.raw_seal.byte_length, right.raw_seal.byte_length);
            assert_eq!(left.raw_seal.sha256, right.raw_seal.sha256);
            assert_eq!(left.raw_seal.encoding, right.raw_seal.encoding);
            assert_eq!(
                left.receipt_oracle.byte_length,
                right.receipt_oracle.byte_length
            );
            assert_eq!(left.receipt_oracle.sha256, right.receipt_oracle.sha256);
            assert_eq!(left.receipt_oracle.encoding, right.receipt_oracle.encoding);
        }

        let catalog = catalog();
        for (left, right) in [(0, 1), (0, 9), (3, 6), (4, 7)] {
            same_evidence_except_paths(&catalog.entries[left], &catalog.entries[right]);
        }
        assert_eq!(catalog.entries[0].claim, catalog.entries[2].claim);
        assert_eq!(
            catalog.entries[0].claim_digest,
            catalog.entries[2].claim_digest
        );
        for index in [5, 6, 8] {
            assert_eq!(catalog.entries[3].claim, catalog.entries[index].claim);
            assert_eq!(
                catalog.entries[3].claim_digest,
                catalog.entries[index].claim_digest
            );
        }
        assert_ne!(catalog.entries[10].claim, catalog.entries[0].claim);
    }

    #[test]
    fn catalog_rejects_coherent_cross_binding_evidence_drift() {
        let mut alias_claim = catalog();
        alias_claim.entries[1].claim.output_digest = "71".repeat(DIGEST_BYTES);
        alias_claim.entries[1].claim_digest =
            hex::encode(recursive_ancestry_claim_digest(&alias_claim.entries[1].claim).unwrap());
        assert!(alias_claim.validate().is_err());

        let mut alias_seal = catalog();
        alias_seal.entries[9].raw_seal.sha256 = "72".repeat(DIGEST_BYTES);
        assert!(alias_seal.validate().is_err());

        let mut third_program = catalog();
        third_program.entries[7].producer_program_id = "73".repeat(DIGEST_BYTES);
        third_program.entries[7].claim.pre_state_digest = "73".repeat(DIGEST_BYTES);
        third_program.entries[7].claim_digest =
            hex::encode(recursive_ancestry_claim_digest(&third_program.entries[7].claim).unwrap());
        assert!(third_program.validate().is_err());

        let mut final_claim = catalog();
        final_claim.entries[5].claim.output_digest = "74".repeat(DIGEST_BYTES);
        final_claim.entries[5].claim_digest =
            hex::encode(recursive_ancestry_claim_digest(&final_claim.entries[5].claim).unwrap());
        assert!(final_claim.validate().is_err());

        let mut duplicate_is_empty = catalog();
        duplicate_is_empty.entries[10].claim = duplicate_is_empty.entries[0].claim.clone();
        duplicate_is_empty.entries[10].claim_digest =
            duplicate_is_empty.entries[0].claim_digest.clone();
        assert!(duplicate_is_empty.validate().is_err());

        let mut distinct_terminal_same_evidence = catalog();
        distinct_terminal_same_evidence.entries[2].raw_seal.sha256 =
            distinct_terminal_same_evidence.entries[0]
                .raw_seal
                .sha256
                .clone();
        distinct_terminal_same_evidence.entries[2]
            .receipt_oracle
            .sha256 = distinct_terminal_same_evidence.entries[0]
            .receipt_oracle
            .sha256
            .clone();
        assert!(distinct_terminal_same_evidence.validate().is_err());

        let mut duplicate_is_alternate_statement = catalog();
        duplicate_is_alternate_statement.entries[10].claim =
            duplicate_is_alternate_statement.entries[3].claim.clone();
        duplicate_is_alternate_statement.entries[10].claim_digest =
            duplicate_is_alternate_statement.entries[3]
                .claim_digest
                .clone();
        assert!(duplicate_is_alternate_statement.validate().is_err());
    }

    #[test]
    fn catalog_binds_the_single_shared_alternate_guest_elf() {
        let value = serde_json::to_value(catalog()).unwrap();
        assert_eq!(
            value["alternateGuestElf"]["path"],
            "reproduction/negative-ancestry-witnesses/alternate-program-guest.elf"
        );
        assert_eq!(value["alternateGuestElf"]["encoding"], "raw-bytes");
        assert!(value["alternateGuestElf"]["byteLength"].as_u64().unwrap() > 0);
        assert_eq!(
            value["alternateProgramId"],
            value["entries"][4]["producerProgramId"]
        );
        assert_eq!(
            value["alternateProgramId"],
            value["entries"][7]["producerProgramId"]
        );
    }

    #[test]
    fn catalog_rejects_missing_extra_reordered_and_semantically_drifted_entries() {
        let mut missing = catalog();
        missing.entries.pop();
        assert!(missing.validate().is_err());

        let mut extra = catalog();
        extra.entries.push(extra.entries[0].clone());
        assert!(extra.validate().is_err());

        let mut reordered = catalog();
        reordered.entries.swap(0, 1);
        assert!(reordered.validate().is_err());

        let mut row = catalog();
        row.entries[0].expanded_row = 140;
        assert!(row.validate().is_err());

        let mut logical = catalog();
        logical.entries[0].logical_consumer_path = logical.entries[0].raw_seal.path.clone();
        assert!(logical.validate().is_err());
    }

    #[test]
    fn catalog_rejects_path_length_digest_program_and_terminal_drift() {
        let mut path = catalog();
        path.entries[0].raw_seal.path = "reproduction/b4nw/999.raw-seal.bin".to_owned();
        assert!(path.validate().is_err());

        let mut length = catalog();
        length.entries[0].raw_seal.byte_length -= 1;
        assert!(length.validate().is_err());

        let mut digest = catalog();
        digest.entries[0].raw_seal.sha256 = "AA".repeat(DIGEST_BYTES);
        assert!(digest.validate().is_err());

        let mut oversized_plan = catalog();
        oversized_plan.negative_plan.byte_length = MAX_NEGATIVE_PLAN_BYTES + 1;
        assert!(oversized_plan.validate().is_err());

        let mut alternate_elf_path = catalog();
        alternate_elf_path.alternate_guest_elf.path =
            "reproduction/negative-ancestry-witnesses/unbound.elf".to_owned();
        assert!(alternate_elf_path.validate().is_err());

        let mut oversized_alternate_elf = catalog();
        oversized_alternate_elf.alternate_guest_elf.byte_length = MAX_ALTERNATE_GUEST_ELF_BYTES + 1;
        assert!(oversized_alternate_elf.validate().is_err());

        let mut claim_digest = catalog();
        claim_digest.entries[0].claim_digest = "01".repeat(DIGEST_BYTES);
        assert!(claim_digest.validate().is_err());

        let mut ordinary_program = catalog();
        ordinary_program.entries[0].producer_program_id = "42".repeat(DIGEST_BYTES);
        ordinary_program.entries[0].claim.pre_state_digest = "42".repeat(DIGEST_BYTES);
        ordinary_program.entries[0].claim_digest = hex::encode(
            recursive_ancestry_claim_digest(&ordinary_program.entries[0].claim).unwrap(),
        );
        assert!(ordinary_program.validate().is_err());

        let mut exceptional_program = catalog();
        exceptional_program.entries[4].producer_program_id =
            exceptional_program.consumer_program_id.clone();
        exceptional_program.entries[4].claim.pre_state_digest =
            exceptional_program.consumer_program_id.clone();
        exceptional_program.entries[4].claim_digest = hex::encode(
            recursive_ancestry_claim_digest(&exceptional_program.entries[4].claim).unwrap(),
        );
        assert!(exceptional_program.validate().is_err());

        let mut terminal = catalog();
        terminal.entries[2].terminal = RecursiveAncestryTerminal::Join {
            control_id: RISC0_JOIN_CONTROL_ID_HEX.to_owned(),
        };
        assert!(terminal.validate().is_err());
    }

    #[cfg(feature = "positive-gate")]
    #[test]
    fn checked_in_schema_accepts_the_rust_catalogue_and_rejects_slot_drift() {
        let schema: Value = serde_json::from_str(include_str!(
            "../finalizer-schema/b4-negative-ancestry-witness-catalog-v1.schema.json"
        ))
        .unwrap();
        let validator = jsonschema::draft202012::options().build(&schema).unwrap();
        let canonical = serde_json::to_value(catalog()).unwrap();
        assert!(validator.validate(&canonical).is_ok());

        let mut wrong_recipe = canonical.clone();
        wrong_recipe["entries"][0]["recipe"] =
            Value::String("reuse-case9-assumption-at-terminal-resolve-step0".to_owned());
        assert!(validator.validate(&wrong_recipe).is_err());

        let mut missing_program = canonical.clone();
        missing_program
            .as_object_mut()
            .unwrap()
            .remove("alternateProgramId");
        assert!(validator.validate(&missing_program).is_err());

        let mut wrong_row_141_terminal = canonical.clone();
        wrong_row_141_terminal["entries"][0]["terminal"] =
            canonical["entries"][10]["terminal"].clone();
        assert!(validator.validate(&wrong_row_141_terminal).is_err());

        let mut wrong_row_154_terminal = canonical.clone();
        wrong_row_154_terminal["entries"][10]["terminal"] =
            canonical["entries"][0]["terminal"].clone();
        assert!(validator.validate(&wrong_row_154_terminal).is_err());

        let mut reordered = canonical;
        reordered["entries"].as_array_mut().unwrap().swap(0, 1);
        assert!(validator.validate(&reordered).is_err());
    }
}
